spring.application.name=lorecraft-backend

spring.datasource.url=jdbc:postgresql://localhost:5432/lorecraft
spring.datasource.username=postgres
spring.datasource.password=06102003

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

server.port=8080